# version = "0.0.4"
display:
  # Display control overlays:
  # 3=Artwork only
  # 2=Full overlay displayed
  # 1=Volume icon only.
  # 0=no overlay displayed
  overlay: 2

  # Display Time Bar:
  # 1=time bar displayed
  # 0=no time bar displayed
  timebar: 1

  # mode=0 for pirate audio and display boards with cs pin
  # mode=3 for display boards without cs pin
  mode: 0

  # Turn backlight off when mpd state=stop
  # back on when play restarted
  # blank=0 screen will not blank when mpd state=stop
  # blank=n screen will blank after roughly n seconds when mpd state=stop
  blank: 0
