# version = "0.0.8"
display:
  # Display control overlays:
  # 3=Full overlay displayed: volume icon+bar and play/pause+next icons (default)
  # 2=Play/pause+next+volume icons (volume bar is shown briefly when volume changes)
  # 1=Volume icon+volume bar overlay only
  # 0=Artwork only - no overlay at all
  overlay: 3

  # Display Time Bar overlay:
  # 1=time bar displayed (default)
  # 0=no time bar displayed
  timebar: 1

  # Display Text overlay:
  # 2=text overlay (artist, album, song title) always displayed (default)
  # 1=text overlay (artist, album, song title) displayed only during play state
  # 0=no text displayed
  text: 2

  # Add shadow to text:
  # Shadow is displayed below and to the right
  # shadow=0 for no shadow text
  # shadow=n with n>0 being the shadow pixel offset (default: 2)
  shadow: 2

  # Cover search priority (as in moOde Preferences->Library)
  # embcoverprio=1 embedded cover (in media file) priority (default)
  # embcoverprio=0 external cover (in media file's directory, i.e. cover.jog) priority
  embcoverprio: 1

  # mode=0 for pirate audio and display boards with cs pin (default)
  # mode=3 for display boards without cs pin
  mode: 0

  # Turn backlight off when mpd state=stop
  # back on when play restarted
  # blank=0 screen will not blank when mpd state=stop (default)
  # blank=n screen will blank after roughly n seconds when mpd state=stop
  blank: 0
